# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b96f02d49621f102816ab61f74d2857f23a6f8d43951b97b6d15b2bcc9db57c8dc511771ade5f3f3fd175c63aa72790276516e781ee7fd1e77e8f8292d4886

test:
  secret_key_base: 9d3f407a92533664c6d66a3c98d6129886c3b036c296daf588a3190bcb6581bc995c9cdfbb282fc012720263483c7bf0906930eb71a256ae0b6fbdd159157428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
